### ISSUE TITLE
capture source and stripLive

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JPaulMora/Pyrit#382]
```
What steps will reproduce the problem?
1. airmon-ng start wlan1
2. mon0  
3. pyrit -r mon0 -o capturepyrit.cap stripLive

What is the expected output? What do you see instead?

Parsing packets from 'mon0'...
Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/lib/pymodules/python2.6/pyrit_cli.py", line 106, in initFromArgv
    func(self, **options)
  File "/usr/lib/pymodules/python2.6/pyrit_cli.py", line 143, in new_f
    f(*args, **kwds)
  File "/usr/lib/pymodules/python2.6/pyrit_cli.py", line 394, in stripLive
    parser.parse_file(capturefile)
  File "/usr/lib/pymodules/python2.6/cpyrit/pckttools.py", line 366, in parse_file
    for pckt in scapy.utils.PcapReader(pcapfile):
  File "/usr/local/lib/python2.6/dist-packages/scapy/utils.py", line 563, in __init__
    RawPcapReader.__init__(self, filename)
  File "/usr/local/lib/python2.6/dist-packages/scapy/utils.py", line 485, in __init__
    self.f = open(filename,"rb")
IOError: [Errno 2] No such file or directory: 'mon0'

What version of the product are you using? On what operating system?

Debian squeeze, Pyrit SVN, Scapy 2.0.1, RTL8187, Python 2.6

Please provide any additional information below.

Interface   Chipset     Driver

wlan1       Realtek RTL8187L    rtl8187 - [phy0]
                (monitor mode enabled on mon0)

```

Original issue reported on code.google.com by `julien.hautefeuille` on 3 Feb 2012 at 6:51

**Comment by algha123** [comment]
Eror

**Comment by algha123** [comment]
script error, please let me know the installation
