### ISSUE TITLE
installation not working - compatible system

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JPaulMora/Pyrit#432]
```
What steps will reproduce the problem?
1. following this guide ( 
http://easymactips.blogspot.com/2011/07/how-to-install-pyrit-cuda-on-mac.html ) 
to:
2. install 
Libnet
http://libdnet.googlecode.com/files/libdnet-1.12.tgz
pylibpcap
http://dfn.dl.sourceforge.net/sourceforge/pylibpcap/pylibpcap-0.6.2.tar.gz  
Scapy
http://www.secdev.org/projects/scapy/files/scapy-latest.tar.gz 
3. try to run any pyrit commands


What version of the product are you using? On what operating system?


Please provide any additional information below.

I attached the terminal output for everything I did.

heres the result of the test_pyrit.py script:

new-host:pyrit Beister$ /Users/Beister/pyrit-read-only/pyrit/test/test_pyrit.py 
 
Testing with filesystem-storage...
testAnalyze (__main__.FilesystemTestCase) ... ERROR
testAttackBatch (__main__.FilesystemTestCase) ... ERROR
testAttackCowpatty (__main__.FilesystemTestCase) ... ERROR
testAttackDB (__main__.FilesystemTestCase) ... ERROR
testAttackPassthrough (__main__.FilesystemTestCase) ... ERROR
testBatch (__main__.FilesystemTestCase) ... ok
testBatchWithFile (__main__.FilesystemTestCase) ... ok
testBenchmark (__main__.FilesystemTestCase) ... ok
testCheckDB (__main__.FilesystemTestCase) ... Error in workunit 
779d06731de94fab22cd0ae408de4991: Digest check failed
Error in workunit dc10ea736c11b8b76cc8d09d5b729317: Digest check failed
Error in workunit e3dbe4a9685fc042f1d8fbc0b4b1f7e0: Not a PAW2-buffer.
Error in workunit 5368d2a0c89836c70f3423a497d74d01: Not a PAW2-buffer.
Error in workunit e104f60a645c7b5e77b0f7aeaf49c231: Digest check failed
Error in workunit bcd1a8054393adae8f59b50600a98de9: Not a PAW2-buffer.
Error in workunit 2e0a246509bb030c8542c0ea743c1416: Not a PAW2-buffer.
Error in workunit 5f73c6c7704e4eae63a05a8e95f07dc1: Digest check failed
Error in results 790eaa350dec3ec3ece44058a38be630 for ESSID 'test': Not a 
PYR2-buffer.
Error in results 1462787072cbc396ab3839fd278b7a32 for ESSID 'test': pmkbuffer 
seems truncated
Error in results c991ad899a818f6f890d4f1128b1c7fd for ESSID 'test': Not a 
PYR2-buffer.
Error in results 01836d318c5e946e8a4e07660d876c3e for ESSID 'test': Not a 
PYR2-buffer.
Error in results d02ecacbb724652a9dbc815635dadc67 for ESSID 'test': Reference 
error
Error in results 5795ac7055c0816aa527103da60a98e8 for ESSID 'test': Reference 
error
Error in results 6cb1061e78ba554ba01a5f9f2475b64f for ESSID 'test': pmkbuffer 
seems truncated
Error in results 612edd3f09a3df83590a5c97d6e3989f for ESSID 'test': Invalid 
ESSID in result-collection
Error in results 0846bb74fd3062a4b660ec1c7ebc685f for ESSID 'test': Not a 
PYR2-buffer.
Error in results 9e33d1992c54e07470272bd625978933 for ESSID 'test': Not a 
PYR2-buffer.
Error in results a346c6c09159a06d4eb0f5be4f344962 for ESSID 'test': Reference 
error
Error in results 0f3c5bc384f24c73608e76a2d4179b7b for ESSID 'test': Reference 
error
Error in results 91b963c7eb10a15fc96733f214d8d4ca for ESSID 'test': pmkbuffer 
seems truncated
Error in results e1bb6dc2f3e0205047034fcae5de9ab0 for ESSID 'test': pmkbuffer 
seems truncated
Error in results 8ca798d6d3473628a1f9ddb511dff62e for ESSID 'test': pmkbuffer 
seems truncated
Error in results 5ca2f1b2fbbd5423c28e7744dc9727a9 for ESSID 'test': Reference 
error
Error in results 69ec96979d43f419c87070080689abb7 for ESSID 'test': pmkbuffer 
seems truncated
Error in results 7aef6d8e984046f89812532a8276e7fc for ESSID 'test': Not a 
PYR2-buffer.
ok
testCreateAndDeleteEssid (__main__.FilesystemTestCase) ... ok
testEval (__main__.FilesystemTestCase) ... ok
testExportCowpatty (__main__.FilesystemTestCase) ... ok
testExportHashdb (__main__.FilesystemTestCase) ... ok
testExportPasswords (__main__.FilesystemTestCase) ... ok
testHandshakes (__main__.FilesystemTestCase) ... ERROR
testImportPasswords (__main__.FilesystemTestCase) ... ok
testListCores (__main__.FilesystemTestCase) ... ok
testListEssids (__main__.FilesystemTestCase) ... ok
testPassthrough (__main__.FilesystemTestCase) ... ok
testPrintHelp (__main__.FilesystemTestCase) ... ok
testSelfTest (__main__.FilesystemTestCase) ... ok
testStripCapture (__main__.FilesystemTestCase) ... ERROR
testStripLive (__main__.FilesystemTestCase) ... ERROR
testVerify (__main__.FilesystemTestCase) ... Workunit 
04daf2a30368a7bb9be230ac2a9a726e for ESSID 'test' is corrupt.
Workunit 4a62095a2dd2aa4b5cb553a1d206df68 for ESSID 'test' is corrupt.
Workunit 61e8c140164cf8d0a54cf2d4b39e7ac0 for ESSID 'test' is corrupt.
Workunit 183f1149e0bfd3f869308ed5ef8bb590 for ESSID 'test' is corrupt.
Workunit 8e77d414c54ab8f0cb7a48824a0f4741 for ESSID 'test' is corrupt.
Workunit 343290766459991686865e4413fa122c for ESSID 'test' is corrupt.
Workunit cd0952df5113eda05ee9b199229d3133 for ESSID 'test' is corrupt.
Workunit b2f0b67e3ff23de0cd490ceb618447c1 for ESSID 'test' is corrupt.
Workunit d2c95f13d6c226b6abe905bc77e45ec7 for ESSID 'test' is corrupt.
Workunit 570e4d9a23ba912b6487865a2f189a09 for ESSID 'test' is corrupt.
Workunit 46d6095371b7757080e71aced3eaff23 for ESSID 'test' is corrupt.
Workunit 97402ef84517bb3b51ac87c9307b9201 for ESSID 'test' is corrupt.
Workunit 84cfe155d1b57f692bb43a419cc9c5ab for ESSID 'test' is corrupt.
Workunit 5bc32c3df7c9977e8897b552634a9e50 for ESSID 'test' is corrupt.
Workunit 4a4e0242b49f18692802323b81f65935 for ESSID 'test' is corrupt.
Workunit c1d0fb9d43881a1251dd3d01c4b80880 for ESSID 'test' is corrupt.
Workunit 59fd5051da958163a7270888d9325177 for ESSID 'test' is corrupt.
Workunit 2d538585b2b318de1cd668f1747e3b5d for ESSID 'test' is corrupt.
Workunit dae6db7dc3b9dd54d57d108235d4c18e for ESSID 'test' is corrupt.
Workunit 86ac117033c15622d04c32abbdc8058a for ESSID 'test' is corrupt.
Workunit f9f06fce5ef954b7e763f884286cfec4 for ESSID 'test' is corrupt.
Workunit 7a96fd789684f3336ae1f58fb5d0a8ff for ESSID 'test' is corrupt.
Workunit aa767e5277c0041d2c1a3513ee4415e9 for ESSID 'test' is corrupt.
ok

======================================================================
ERROR: testAnalyze (__main__.FilesystemTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Beister/pyrit-read-only/pyrit/test/test_pyrit.py", line 63, in new_f
    f(*args, **kwds)
  File "/Users/Beister/pyrit-read-only/pyrit/test/test_pyrit.py", line 453, in testAnalyze
    self.cli.analyze(capturefile='wpapsk-linksys.dump.gz')
  File "/Library/Python/2.7/site-packages/pyrit_cli.py", line 165, in new_f
    f(*args, **kwds)
  File "/Library/Python/2.7/site-packages/pyrit_cli.py", line 449, in analyze
    parser = self._getParser(capturefile)
  File "/Library/Python/2.7/site-packages/pyrit_cli.py", line 175, in _getParser
    capturefilemask)
PyritRuntimeError: No file found that matches 'wpapsk-linksys.dump.gz'

======================================================================
ERROR: testAttackBatch (__main__.FilesystemTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Beister/pyrit-read-only/pyrit/test/test_pyrit.py", line 63, in new_f
    f(*args, **kwds)
  File "/Users/Beister/pyrit-read-only/pyrit/test/test_pyrit.py", line 250, in testAttackBatch
    self.cli.attack_batch(storage, 'wpapsk-linksys.dump.gz')
  File "/Library/Python/2.7/site-packages/pyrit_cli.py", line 165, in new_f
    f(*args, **kwds)
  File "/Library/Python/2.7/site-packages/pyrit_cli.py", line 985, in attack_batch
    ap = self._fuzzyGetAP(self._getParser(capturefile), bssid, essid)
  File "/Library/Python/2.7/site-packages/pyrit_cli.py", line 175, in _getParser
    capturefilemask)
PyritRuntimeError: No file found that matches 'wpapsk-linksys.dump.gz'

======================================================================
ERROR: testAttackCowpatty (__main__.FilesystemTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Beister/pyrit-read-only/pyrit/test/test_pyrit.py", line 63, in new_f
    f(*args, **kwds)
  File "/Users/Beister/pyrit-read-only/pyrit/test/test_pyrit.py", line 243, in testAttackCowpatty
    self.cli.attack_cowpatty('wpapsk-linksys.dump.gz', self.tempfile1)
  File "/Library/Python/2.7/site-packages/pyrit_cli.py", line 165, in new_f
    f(*args, **kwds)
  File "/Library/Python/2.7/site-packages/pyrit_cli.py", line 1116, in attack_cowpatty
    ap = self._fuzzyGetAP(self._getParser(capturefile), bssid, essid)
  File "/Library/Python/2.7/site-packages/pyrit_cli.py", line 175, in _getParser
    capturefilemask)
PyritRuntimeError: No file found that matches 'wpapsk-linksys.dump.gz'

======================================================================
ERROR: testAttackDB (__main__.FilesystemTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Beister/pyrit-read-only/pyrit/test/test_pyrit.py", line 63, in new_f
    f(*args, **kwds)
  File "/Users/Beister/pyrit-read-only/pyrit/test/test_pyrit.py", line 235, in testAttackDB
    self.cli.attack_db(storage, 'wpapsk-linksys.dump.gz')
  File "/Library/Python/2.7/site-packages/pyrit_cli.py", line 165, in new_f
    f(*args, **kwds)
  File "/Library/Python/2.7/site-packages/pyrit_cli.py", line 1047, in attack_db
    ap = self._fuzzyGetAP(self._getParser(capturefile), bssid, essid)
  File "/Library/Python/2.7/site-packages/pyrit_cli.py", line 175, in _getParser
    capturefilemask)
PyritRuntimeError: No file found that matches 'wpapsk-linksys.dump.gz'

======================================================================
ERROR: testAttackPassthrough (__main__.FilesystemTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Beister/pyrit-read-only/pyrit/test/test_pyrit.py", line 63, in new_f
    f(*args, **kwds)
  File "/Users/Beister/pyrit-read-only/pyrit/test/test_pyrit.py", line 486, in testAttackPassthrough
    self.cli.attack_passthrough(self.tempfile1, 'wpapsk-linksys.dump.gz')
  File "/Library/Python/2.7/site-packages/pyrit_cli.py", line 165, in new_f
    f(*args, **kwds)
  File "/Library/Python/2.7/site-packages/pyrit_cli.py", line 917, in attack_passthrough
    ap = self._fuzzyGetAP(self._getParser(capturefile), bssid, essid)
  File "/Library/Python/2.7/site-packages/pyrit_cli.py", line 175, in _getParser
    capturefilemask)
PyritRuntimeError: No file found that matches 'wpapsk-linksys.dump.gz'

======================================================================
ERROR: testHandshakes (__main__.FilesystemTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Beister/pyrit-read-only/pyrit/test/test_pyrit.py", line 63, in new_f
    f(*args, **kwds)
  File "/Users/Beister/pyrit-read-only/pyrit/test/test_pyrit.py", line 449, in testHandshakes
    self._testHandshake(filename, essid, ap, sta, passwd)
  File "/Users/Beister/pyrit-read-only/pyrit/test/test_pyrit.py", line 165, in _testHandshake
    parser = cpyrit.pckttools.PacketParser(filename)
  File "/Library/Python/2.7/site-packages/cpyrit/pckttools.py", line 623, in __init__
    self.parse_file(pcapfile)
  File "/Library/Python/2.7/site-packages/cpyrit/pckttools.py", line 663, in parse_file
    with PcapDevice(pcapfile, self.use_bpf) as rdr:
  File "/Library/Python/2.7/site-packages/cpyrit/pckttools.py", line 491, in __init__
    self.open_offline(fname)
  File "/Library/Python/2.7/site-packages/cpyrit/pckttools.py", line 561, in open_offline
    with util.FileWrapper(fname) as infile:
  File "/Library/Python/2.7/site-packages/cpyrit/util.py", line 255, in __init__
    self.f = gzip.open(filename, mode, 6)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 89, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: 'wpapsk-linksys.dump.gz'

======================================================================
ERROR: testStripCapture (__main__.FilesystemTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Beister/pyrit-read-only/pyrit/test/test_pyrit.py", line 63, in new_f
    f(*args, **kwds)
  File "/Users/Beister/pyrit-read-only/pyrit/test/test_pyrit.py", line 461, in testStripCapture
    self.cli.stripCapture('wpapsk-linksys.dump.gz', self.tempfile1)
  File "/Library/Python/2.7/site-packages/pyrit_cli.py", line 165, in new_f
    f(*args, **kwds)
  File "/Library/Python/2.7/site-packages/pyrit_cli.py", line 480, in stripCapture
    parser = self._getParser(capturefile)
  File "/Library/Python/2.7/site-packages/pyrit_cli.py", line 175, in _getParser
    capturefilemask)
PyritRuntimeError: No file found that matches 'wpapsk-linksys.dump.gz'

======================================================================
ERROR: testStripLive (__main__.FilesystemTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Beister/pyrit-read-only/pyrit/test/test_pyrit.py", line 63, in new_f
    f(*args, **kwds)
  File "/Users/Beister/pyrit-read-only/pyrit/test/test_pyrit.py", line 473, in testStripLive
    self.cli.stripLive('wpa2psk-linksys.dump.gz', self.tempfile1)
  File "/Library/Python/2.7/site-packages/pyrit_cli.py", line 165, in new_f
    f(*args, **kwds)
  File "/Library/Python/2.7/site-packages/pyrit_cli.py", line 580, in stripLive
    str(offline_error), str(live_error)))
PyritRuntimeError: Failed to open 'wpa2psk-linksys.dump.gz' either as a file 
('[Errno 2] No such file or directory: 'wpa2psk-linksys.dump.gz'') or as a 
device ('Failed to open device 'wpa2psk-linksys.dump.gz' (libpcap: 
wpa2psk-linksys.dump.gz: No such device exists (BIOCSETIF failed: Device not 
configured))')

----------------------------------------------------------------------
Ran 24 tests in 67.329s

FAILED (errors=8)
```

Original issue reported on code.google.com by `chy...@gmail.com` on 12 May 2013 at 11:10

Attachments:
* [terminaloutput5 11 13](https://storage.googleapis.com/google-code-attachments/pyrit/issue-432/comment-0/terminaloutput5 11 13)

**Comment by JPaulMora** [comment]
well it looks pyrit is not in your PATH.
