### ISSUE TITLE
pyrit server

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JPaulMora/Pyrit#439]
```
hi i have problems with Pyrite server
get it when I run Pyrite benchmark on the client
detested is what gets on Pyrite server

plis help!!!


Please provide any additional information below.
Serving 1 active clients; 0 PMKs/s; 0.0 TTS Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/network.py", line 55, in run
    self.client.enqueue(essid, pwlist)
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/network.py", line 103, in enqueue
    self.enqueue_callback(self.uuid, (essid, pwlist))
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/network.py", line 153, in enqueue
    self.cp.enqueue(essid, pwlist)
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 566, in enqueue
    passwordlist = list(passwords)
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/storage.py", line 156, in __iter__
    return self.collection.__iter__()
AttributeError: 'str' object has no attribute '__iter__'

plis help!!!
```

Original issue reported on code.google.com by `keiko...@gmail.com` on 11 Sep 2013 at 11:10

**Comment by JPaulMora** [comment]
Latest version fixes the issue.
