### ISSUE TITLE
./_cpyrit_cudakernel.cu' returned non-zero exit status 1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JPaulMora/Pyrit#440]
```
192:cpyrit_cuda macbook-pro$ sudo LDFLAGS=-L/usr/local/cuda/lib python setup.py 
install
running install
running build
running build_ext
Compiling CUDA module using nvcc 5.0, V0.2.1221...
Executing '/usr/local/cuda/bin/nvcc -m64 --host-compilation C -Xcompiler 
"-fPIC" --ptx ./_cpyrit_cudakernel.cu'
nvcc warning : option 'host-compilation' has been deprecated and is ignored
clang: error: unsupported option '-dumpspecs'
clang: error: no input files
Traceback (most recent call last):
  File "setup.py", line 175, in <module>
    setup(**setup_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 573, in run
    self.run_command('build')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 100, in run
    subprocess.check_call(nvcc_cmd, shell=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/cuda/bin/nvcc -m64 
--host-compilation C -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu' returned 
non-zero exit status 1


Pyrit 0.4.1-dev on a Macbook Pro 15" Medio 2012 MacOS X 10.8.5 nVidia GeForce 
GT650M 512Mb 4Gb MBP9,1

Pyrit already installed, but can't install cPyrit
```

Original issue reported on code.google.com by `cornerst...@hotmail.com` on 22 Oct 2013 at 5:39

**Comment by JPaulMora** [comment]
Cpyrit-CUDA is broken for Xcode 7, also closing as unhelpful.
