### ISSUE TITLE
CL_DEVICE_NOT_FOUND

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JPaulMora/Pyrit#453]
```
When I try to start pyrit (pyrit-svn r308) with the cpyrit_opencl extension I 
get this error:
(I have an ATI GPU and I'm using the OpenSource driver with mesa-opencl 
installed )


Traceback (most recent call last):
  File "/usr/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/lib/python2.7/site-packages/pyrit_cli.py", line 117, in initFromArgv
    func(self, **options)
  File "/usr/lib/python2.7/site-packages/pyrit_cli.py", line 805, in batchprocess
    yieldOldResults=cowpwriter is not None) as dbiterator:
  File "/usr/lib/python2.7/site-packages/cpyrit/cpyrit.py", line 727, in __init__
    self.cp = CPyrit() if yieldNewResults else None
  File "/usr/lib/python2.7/site-packages/cpyrit/cpyrit.py", line 446, in __init__
    p = _cpyrit_opencl.OpenCLPlatform(platform_idx)
SystemError: Failed to enumerate devices on this platform (CL_DEVICE_NOT_FOUND)
```

Original issue reported on code.google.com by `MangaMan...@gmail.com` on 15 Jun 2014 at 4:14

**Comment by JPaulMora** [comment]
Closing as oudated.
