### ISSUE TITLE
error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JPaulMora/Pyrit#459]
```
crunch 8 24 abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 | 
pyrit -r 1.cap -i – -b b4:75:0e:84:67:e2 attack_passthrough
Crunch will now generate the following amount of data: 9369628950964642048 bytes
8935574484791 MB
8726146957 GB
8521627 TB
8321 PB
Crunch will now generate the following number of lines: 853054792520188672 
Pyrit 0.4.0 (C) 2008-2011 Lukas Lueg http://pyrit.googlecode.com
This code is distributed under the GNU General Public License v3+

Parsing file '1.cap' (1/1)...
Parsed 4 packets (4 802.11-packets), got 1 AP(s)

Traceback (most recent call last):
  File "/usr/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/lib/pymodules/python2.7/pyrit_cli.py", line 115, in initFromArgv
    func(self, **options)
  File "/usr/lib/pymodules/python2.7/pyrit_cli.py", line 163, in new_f
    f(*args, **kwds)
  File "/usr/lib/pymodules/python2.7/pyrit_cli.py", line 927, in attack_passthrough
    with cpyrit.util.FileWrapper(infile) as reader:
  File "/usr/lib/pymodules/python2.7/cpyrit/util.py", line 132, in __init__
    self.f = open(filename, mode)
IOError: [Errno 2] No such file or directory: '\xe2\x80\x93'
root@lsd:~# 

```

Original issue reported on code.google.com by `xswe...@gmail.com` on 23 Aug 2014 at 12:36

**Comment by JPaulMora** [comment]
Please confirm if this bug is still present.
