### ISSUE TITLE
CUDA_ERROR_NO_BINARY_FOR_GPU

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JPaulMora/Pyrit#460]
```
What steps will reproduce the problem?
1. Clean install of pyrit with cuda
2. Run pyrit list_cores
3.

What is the expected output? What do you see instead?
I expect the cores (mine is GeForce GT 330M)

what I see instead is:
Pyrit 0.4.1-dev (svn r308) (C) 2008-2011 Lukas Lueg http://pyrit.googlecode.com
This code is distributed under the GNU General Public License v3+

Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/Library/Python/2.7/site-packages/pyrit_cli.py", line 117, in initFromArgv
    func(self, **options)
  File "/Library/Python/2.7/site-packages/pyrit_cli.py", line 293, in list_cores
    with cpyrit.cpyrit.CPyrit() as cp:
  File "/Library/Python/2.7/site-packages/cpyrit/cpyrit.py", line 440, in __init__
    self.cores.append(CUDACore(queue=self, dev_idx=dev_idx))
  File "/Library/Python/2.7/site-packages/cpyrit/cpyrit.py", line 245, in __init__
    _cpyrit_cuda.CUDADevice.__init__(self, dev_idx)
SystemError: CUDA_ERROR_NO_BINARY_FOR_GPU

What version of the product are you using? On what operating system?

I'm using the latest svn, on OSX 10.9.4. Pyrit is working fine, cpyrit installs 
without issues after modify setup.py to identify the path for nvcc. But it 
doesn't run properly as I reported above. CUDA drivers and toolkit are 6.5.14. 

Please provide any additional information below.

I've followed the instructions to test CUDA: it is working properly on my 
system (I've tested all of the samples that come with the toolkit). I checked 
the previous posts for similar issues. Some of them seem similar but the 
solutions do not fit my specific case. I've checked google and the various 
tutorials and guides. Probably I'm missing something stupid. But it is missing. 
Annoying.
```

Original issue reported on code.google.com by `francesc...@gmail.com` on 13 Sep 2014 at 9:06

**Comment by JPaulMora** [comment]
Please try OpenCL for now.
