### ISSUE TITLE
KeyError: 'ATISTREAMSDKROOT'

### ISSUE THREAD

**Issue by zjhxmjl** [JPaulMora/Pyrit#489]
zjhxmjl@ubuntu:~/pyrit-0.4.0/cpyrit_calpp$ python setup.py build
running build
running build_ext
Building modules...
zjhxmjl@ubuntu:~/pyrit-0.4.0/cpyrit_calpp$ sudo python setup.py install 
unavailable enviroment variable ATISTREAMSDKROOT
Traceback (most recent call last):
  File "setup.py", line 35, in <module>
    CALPP_INC_DIR = os.environ['ATISTREAMSDKROOT']
  File "/usr/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'ATISTREAMSDKROOT'

i don't know why ATISTREAMSDKROOT is unavailable enviroment variable.can you give some advance?
i followed this guide https://forums.kali.org/showthread.php?19285-Installing-ATI-drivers-AMD-APP-SDK-CAL-and-Pyrit

**Comment by JPaulMora** [comment]
according to your guide:

````
# add these lines to ~/.bashrc
# AMD APP SDK
export AMDAPPSDKROOT=/opt/AMDAPP
export AMDAPPSDKSAMPLESROOT=/opt/AMDAPP/
export LD_LIBRARY_PATH=${AMDAPPSDKROOT}lib/x86_64:${LD_LIBRARY_PATH}
export ATISTREAMSDKROOT=$AMDAPPSDKROOT

##then do 
source ~/.bashrc
````

**Comment by mengxiaolin** [comment]
hi zjhxmjl, I encountered the same problem, but JPauIMora's solution does not work,  I edited the setup.py file and changed the try CALPP_INC_DIR = os.environ['ATISTREAMSDKROOT'] line to
CALPP_INC_DIR = '/opt/AMDAPP' and everything works finally. I think something is wrong with the setup file when doing install command.
