### ISSUE TITLE
global name 'cpyrit_cuda' is not defined

### ISSUE THREAD

**Issue by Fullatx** [JPaulMora/Pyrit#496]
Hey, first thx for your work ,

Im running into an issue after installing Pyrit 0.5.0 and Cpyrit_cuda , when i try to do pyrit list_cores i get this : 

root@Lika:~/Downloads/Pyrit-0.5.0/modules/cpyrit_cuda# pyrit list_cores
Pyrit 0.5.0 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 117, in initFromArgv
    func(self, **options)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 294, in list_cores
    with cpyrit.cpyrit.CPyrit() as cp:
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 441, in __init__
    CUDA =  cpyrit_cuda.listDevices()
NameError: global name 'cpyrit_cuda' is not defined

**Comment by Fullatx** [comment]
i have not output from python -c 'from cpyrit import _cpyrit_cuda' , from troubleshooting its say if not output that mean its already loaded, but i still get 

Pyrit 0.5.0 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 117, in initFromArgv
    func(self, **options)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 294, in list_cores
    with cpyrit.cpyrit.CPyrit() as cp:
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 441, in __init__
    CUDA =  cpyrit_cuda.listDevices()
NameError: global name 'cpyrit_cuda' is not defined

**Comment by JPaulMora** [comment]
Try reinstalling pyrit_cuda. I'll try to replicate the issue and post any updates.

**Comment by Fullatx** [comment]
during re installing cpyrit_cuda : 

 building : 
running build
running build_ext
Skipping rebuild of Nvidia CUDA kernel ...
Building modules...

root@Lika:~/Downloads/Pyrit-0.5.0/modules/cpyrit_cuda# python setup.py install
running install
running build
running build_ext
Skipping rebuild of Nvidia CUDA kernel ...
Building modules...
running install_lib
copying build/lib.linux-x86_64-2.7/cpyrit/_cpyrit_cuda.so -> /usr/local/lib/python2.7/dist-packages/cpyrit
running install_egg_info
Writing /usr/local/lib/python2.7/dist-packages/cpyrit_cuda-0.5.0.egg-info
 
and when launching a list_cores, still getting previus error, do you see anything wrong in my install ?

**Comment by JPaulMora** [comment]
could you try installing the latest version from the master branch? I remember a similar issue was fixed not so long ago. `git clone https://github.com/JPaulMora/Pyrit.git`

**Comment by Fullatx** [comment]
with last version i get a new type of error : 

Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 118, in initFromArgv
    func(self, **options)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 295, in list_cores
    with cpyrit.cpyrit.CPyrit() as cp:
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 442, in __init__
    self.CUDAs.append(CUDACore(queue=self, dev_idx=dev_idx))
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 243, in __init__
    _cpyrit_cuda.CUDADevice.__init__(self, dev_idx)
SystemError: CUDA_ERROR_NO_BINARY_FOR_GPU

**Comment by Fullatx** [comment]
with only open cl module, when i list my cores i only get cores from cpu

**Comment by JPaulMora** [comment]
I see, did you enable OpenCL in config?

`SystemError: CUDA_ERROR_NO_BINARY_FOR_GPU`: There was someone posting this issue a few days ago, looks like the kernel isn't being compiled. I will keep updates regarding this in the other issue.

**Comment by puneet336** [comment]
This seems to be a bug within the stable release (0.5.0)- https://github.com/JPaulMora/Pyrit/archive/v0.5.0.zip. Within file cpyrit/cpyrit.py , there must be _cpyrit_cuda.listDevices() instead of  cpyrit_cuda.cuda.listDevices()
Though this further gives rise to additional issues.


This issue seems to have been fixed in the master version -
[user@gpul01 ~]$ pyrit list_cores
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

The following cores seem available...
#1:  'CPU-Core (SSE2/AES)'
#2:  'CPU-Core (SSE2/AES)'
#3:  'CPU-Core (SSE2/AES)'
#4:  'CPU-Core (SSE2/AES)'
#5:  'CPU-Core (SSE2/AES)'
#6:  'CPU-Core (SSE2/AES)'
#7:  'CPU-Core (SSE2/AES)'
#8:  'CPU-Core (SSE2/AES)'
#9:  'CPU-Core (SSE2/AES)'
#10:  'CPU-Core (SSE2/AES)'
#11:  'CPU-Core (SSE2/AES)'
#12:  'CPU-Core (SSE2/AES)'
#13:  'CPU-Core (SSE2/AES)'
#14:  'CPU-Core (SSE2/AES)'
#15:  'CPU-Core (SSE2/AES)'
#16:  'CPU-Core (SSE2/AES)'
#17:  'CPU-Core (SSE2/AES)'
#18:  'CPU-Core (SSE2/AES)'
#19:  'CPU-Core (SSE2/AES)'
#20:  'CPU-Core (SSE2/AES)'
#21:  'CPU-Core (SSE2/AES)'
#22:  'CPU-Core (SSE2/AES)'
#23:  'CPU-Core (SSE2/AES)'
#24:  'CPU-Core (SSE2/AES)'

The following CUDA GPUs seem aviable...
#1:  'CUDA-Device #1 'Tesla K40m''
#2:  'CUDA-Device #2 'Tesla K40m''
