### ISSUE TITLE
CUDA_ERROR_NO_BINARY_FOR_GPU

### ISSUE THREAD

**Issue by mittso** [JPaulMora/Pyrit#497]
Hi, thx for your work ,

Im running into an issue after installing Pyrit 0.5.1 and Cpyrit_cuda , when i try to do: 
**optirun pyrit list_cores** i get this : 

Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 118, in initFromArgv
    func(self, **options)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 295, in list_cores
    with cpyrit.cpyrit.CPyrit() as cp:
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 442, in __init__
    self.CUDAs.append(CUDACore(queue=self, dev_idx=dev_idx))
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 243, in __init__
    _cpyrit_cuda.CUDADevice.__init__(self, dev_idx)
SystemError: CUDA_ERROR_NO_BINARY_FOR_GPU

I have not output from: **optirun python -c 'from cpyrit import _cpyrit_cuda'**

My setup: 
Razer Blade 2013 laptop (GTX 765M).
Linux kali 4.7.0-kali1-amd64 #1 SMP Debian 4.7.5-1kali3 (2016-09-29) x86_64 GNU/Linux
nvidia-driver v367.44-2 (form repos).
nvidia-cuda-toolkit v7.5.18-4 (form repos).

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17

**Comment by JuniorGandara** [comment]
Same issue

**Comment by mittso** [comment]
It seems that the problem was with the driver. After I've upgraded to nvidia-driver v367.44-3 the problem disappeared.

**Comment by JPaulMora** [comment]
glad to hear that
