### ISSUE TITLE
Client task halts when server task is interrupted.

### ISSUE THREAD

**Issue by xflyboy** [JPaulMora/Pyrit#502]
Thanks for making SERVE/CLIENT modules for this tool. hope you still working on it.

I have a Master Desktop Motherboard:ASUS P5Q - 771 MOD
Procesador (CPU): Intel® Xeon® Processor X5450 (12M Cache, 3.00 GHz, 1333 MHz FSB)
Memoria RAM: DDR 4GB
Placa de Video (GPU): EVGA NVIDIA GForce GTX 750 TI FTW ACS 2Gb

Added server Laptop: Intel i7-4510u 2.6 + HD Intel + CUDA 7 Nvidia GForce 840M Aprox 32.000 K/s Mint 18
and it was working all good till i closed the lid of the laptop.
Server halted. Laptop gave an error which i will add in next post.

Both Mint 18. Pyrit 0.5.1

**Comment by xflyboy** [comment]
Laptop output. 
``max@hp ~ $ pyrit serve
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Serving 1 active clients; 32945 PMKs/s; 0.0 TTS Exception in thread CUDA-Device #1 'GeForce 840M':
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 115, in run
    res = self.solve(essid, pwlist)
SystemError: CUDA_ERROR_LAUNCH_FAILED

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/network.py", line 56, in run
    self.client.enqueue(essid, pwlist)
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/network.py", line 104, in enqueue
    self.enqueue_callback(self.uuid, (essid, pwlist))
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/network.py", line 154, in enqueue
    self.cp.enqueue(essid, pwlist)
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 575, in enqueue
    self._check_cores()
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 501, in _check_cores
    raise SystemError("The core '%s' has died unexpectedly" % core)
SystemError: The core 'CUDA-Device #1 'GeForce 840M'' has died unexpectedly

Serving 1 active clients; 17863 PMKs/s; 0.3 TTS Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/network.py", line 176, in run
    raise RuntimeError
RuntimeError

Serving 0 active clients; 17888 PMKs/s; 0.3 TTS max@hp ~ $ pyrit serve
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 118, in initFromArgv
    func(self, **options)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 892, in serve
    server = cpyrit.network.NetworkServer()
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/network.py", line 122, in __init__
    self.cp = cpyrit.CPyrit()
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 442, in __init__
    self.CUDAs.append(CUDACore(queue=self, dev_idx=dev_idx))
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 243, in __init__
    _cpyrit_cuda.CUDADevice.__init__(self, dev_idx)
SystemError: CUDA_ERROR_UNKNOWN
max@hp ~ $ ^C
max@hp ~ $  '

**Comment by casept** [comment]
> SystemError: The core 'CUDA-Device #1 'GeForce 840M'' has died unexpectedly

Seems like your laptop kills the GPU when the lid is closed.

**Comment by xflyboy** [comment]
I can handle the Laptop lid.
the problem i was describing is that Client halts. This should not be happening.

**Comment by JPaulMora** [comment]
I see what you mean, you're expecting the client to remain on a paused state until server resumes work  is that right?

**Comment by xflyboy** [comment]
Not really. Client can still work properly and look for possible Servers.  It shouldn't stop in best cases.

**Comment by JPaulMora** [comment]
Its not possible for the client to keep hashing when the server is halted, if that's what you wanted. Alternatively you could setup an Always-on SQL database and use it for Pyrit storage, so that you can leave a client hashing solo when your main CPU has to be offline.
