### ISSUE TITLE
'cpyrit_cuda' is not defined

### ISSUE THREAD

**Issue by AxissXs** [JPaulMora/Pyrit#504]
pyrit list_cores returns these

Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 117, in initFromArgv
    func(self, **options)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 294, in list_cores
    with cpyrit.cpyrit.CPyrit() as cp:
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 441, in __init__
    CUDA =  cpyrit_cuda.listDevices()
NameError: global name 'cpyrit_cuda' is not defined

**Comment by AxissXs** [comment]
would somebody like to say a heartwarming word at least?

**Comment by JPaulMora** [comment]
Hi, what version of Pyrit are you using? 

> The CUDA compiler and headers required to build kernel were not found. Trying to continue anyway...

This means you probably haven't installed the CUDA dev-toolkit or (as it says) Pyrit can't find them

**Comment by AxissXs** [comment]
i got the latest version installed
i installed cuda but i don't know why it can't find it, my nvidia driver also doesn't work correctly because of x11 conf file, i used nvidia-xconfig but it just messed up and didn't work. any tips?

**Comment by RFKiller** [comment]
@AxissXs - are you still interested in building Pyrit with CUDA? Because I think I know exactly what your issues are, as I've faced similar ones in the past.

1. CUDA is installed, not the CUDA development headers (which are needed to build CUDA programs)
2. You used nvidia-xconfig and now Xorg won't load your Nvidia driver when Xorg starts.

Would you like to know exactly what steps I took to successfully build Pyrit with CUDA? Or have you figured it out yourself now? Or are you simply no longer interested?

**Comment by AxissXs** [comment]
@PFKiller thanks for you answer, i'm still stuck with it, actually i gave up cause i had more important works to do, i'm all eyes to read your solution my friend

btw, i don't use nvidia-xconfig, for idk what reason it screws up my xorg, so when i reboot nothing will come up, only a blank (then switch to tty1 and delete xorg config file to fix it), i still doubt if my linux is working with my nvidia drivers correctly

**Comment by JPaulMora** [comment]
What OS are you in?

**Comment by AxissXs** [comment]
i'm on ParrotSec
