### ISSUE TITLE
Error while parsing - AttributeError

### ISSUE THREAD

**Issue by Muzgar15** [JPaulMora/Pyrit#506]
Whenever I try to analyze a capture file or attack a handshake or do anything with a capture file I get the following output: 

 >Pyrit 0.5.0 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+
Parsing file 'duend-01.cap' (1/1)...
Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 117, in initFromArgv
    func(self, **options)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 166, in new_f
    f(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 497, in stripCapture
    parser = self._getParser(capturefile)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 182, in _getParser
    parser.parse_pcapdevice(dev)
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 697, in parse_pcapdevice
    self.parse_packet(pckt)
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 710, in parse_packet
    if dot11_pckt.isFlagSet('type', 'Control'):
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 67, in isFlagSet
    return (1 << field.names.index([value])) & self.__getattr__(name) != 0
AttributeError: 'BitEnumField' object has no attribute 'names'

**Comment by strasharo** [comment]
https://github.com/JPaulMora/Pyrit/issues/500
