### ISSUE TITLE
Handshake Problem

### ISSUE THREAD

**Issue by marsalansiddiqui** [JPaulMora/Pyrit#509]
Here is the official post for this problem. It is more or less a problem with pyrit.

Step 1. Analyze the cap file
pyrit -r file.cap analyze

What it should look like

Pyrit 0.4.0 (C) 2008-2011 Lukas Lueg http://pyrit.googlecode.com
This code is distributed under the GNU General Public License v3+
Parsing file '.cap' (1/1)...
Parsed 1 packets (1 802.11-packets), got 1 AP(s)
#1: AccessPoint ('TP-LINK_'):
No valid EAOPL-handshake + ESSID detected.
Here is the output of a truncated cap

Parsing file '.cap' (1/1)...
Traceback (most recent call last):
File "/usr/bin/pyrit", line 6, in 
pyrit_cli.Pyrit_CLI().initFromArgv()
File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 115, in initFromArgv
func(self, **options)
File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 163, in new_f
f(*args, **kwds)
File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 447, in analyze
parser = self._getParser(capturefile)
File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 179, in _getParser
parser.parse_pcapdevice(dev)
File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 600, in parse_pcapdevice
for pckt in reader:
File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 500, in next
pckt = self.read()
File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 488, in read
r = _cpyrit_cpu.PcapDevice.read(self)
IOError: libpcap-error while reading: truncated dump file; tried to read 414 captured bytes, only got 158
Solve this Problem
pyrit -r old.cap -o new.cap stripLive

We use only packages which are necessary for the eapol handshake detection, and write this in a new file.

Analyze the new cap
pyrit -r new.cap analyze

**Comment by bacondropped** [comment]
Can you reproduce this with the dev branch? `pip install git+https://github.com/JPaulMora/Pyrit@dev`

If yes, could you attach the problematic pcap (or find one here: https://wiki.wireshark.org/SampleCaptures)?
