### ISSUE TITLE
Error Critical!

### ISSUE THREAD

**Issue by its0x08** [JPaulMora/Pyrit#512]
what the hell is wrong ?! help please

root@kali:~/Desktop# pyrit -r badwifi.cap -e Bad\ Wi-Fi attack_batch
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Connecting to storage at 'file://'...  connected.
Parsing file 'badwifi.cap' (1/1)...
Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 118, in initFromArgv
    func(self, **options)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 167, in new_f
    f(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 1003, in attack_batch
    ap = self._fuzzyGetAP(self._getParser(capturefile), bssid, essid)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 183, in _getParser
    parser.parse_pcapdevice(dev)
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 689, in parse_pcapdevice
    self.parse_packet(pckt)
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 702, in parse_packet
    if dot11_pckt.isFlagSet('type', 'Control'):
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 67, in isFlagSet
    return (1 << field.names.index([value])) & self.__getattr__(name) != 0
AttributeError: 'BitEnumField' object has no attribute 'names'

**Comment by chetanpm** [comment]
I get the error in same pattern:

Chetans-MacBook-Pro:test chetanpm$ pyrit -r wpapsk-linksys.dump.gz -i dict.gz -b 00:0b:86:c2:a4:85 attack_passthrough
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Parsing file 'wpapsk-linksys.dump.gz' (1/1)...
Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/local/lib/python2.7/site-packages/pyrit_cli.py", line 118, in initFromArgv
    func(self, **options)
  File "/usr/local/lib/python2.7/site-packages/pyrit_cli.py", line 167, in new_f
    f(*args, **kwds)
  File "/usr/local/lib/python2.7/site-packages/pyrit_cli.py", line 935, in attack_passthrough
    ap = self._fuzzyGetAP(self._getParser(capturefile), bssid, essid)
  File "/usr/local/lib/python2.7/site-packages/pyrit_cli.py", line 183, in _getParser
    parser.parse_pcapdevice(dev)
  File "/usr/local/lib/python2.7/site-packages/cpyrit/pckttools.py", line 689, in parse_pcapdevice
    self.parse_packet(pckt)
  File "/usr/local/lib/python2.7/site-packages/cpyrit/pckttools.py", line 702, in parse_packet
    if dot11_pckt.isFlagSet('type', 'Control'):
  File "/usr/local/lib/python2.7/site-packages/cpyrit/pckttools.py", line 67, in isFlagSet
    return (1 << field.names.index([value])) & self.__getattr__(name) != 0
AttributeError: 'BitEnumField' object has no attribute 'names'

**Comment by rhertzog** [comment]
This is already fixed in the dev branch:
https://github.com/JPaulMora/Pyrit/commit/14ec997174b8e8fd20d22b6a97c57e19633f12a0

**Comment by JPaulMora** [comment]
Sorry for late replay, I will merge dev branch to Master

**Comment by chetanpm** [comment]
@JPaulMora >Latest commit 6111f10  on Aug 16, 2016

Its been a while since any action buddy, Is the merge going to happen anytime in the horizon??
