### ISSUE TITLE
Does anyone know the cause/fix for this? ValueError with Pyrit

### ISSUE THREAD

**Issue by HelenHHH** [JPaulMora/Pyrit#518]
Does anyone know the cause/fix for this? 
It happened right after I did a: apt-get update/upgrade/dist-upgrade
(Worked prior to that.)

root@kali:~# pyrit -r 60.cap attack_db

Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Connecting to storage at 'file://'...  connected.
Parsing file '60.cap' (1/1)...
Traceback (most recent call last):
  File "/usr/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 118, in initFromArgv
    func(self, **options)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 167, in new_f
    f(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 1065, in attack_db
    ap = self._fuzzyGetAP(self._getParser(capturefile), bssid, essid)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 183, in _getParser
    parser.parse_pcapdevice(dev)
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 700, in parse_pcapdevice
    self.parse_packet(pckt)
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 730, in parse_packet
    if dot11_pckt.isFlagSet('FCfield', 'to-DS') \
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 78, in isFlagSet
    return (1 << field.names.index([value])) & self.__getattr__(name) != 0
ValueError: ['to-DS'] is not in list

root@kali:~#

**Comment by RFKiller** [comment]
I'm going to go out on a limb here and say Kali Linux broke Pyrit when they upgraded it, or broke a dependency for Pyrit. The easiest way to figure it out is to clone Pyrit and try building it yourself and see what the outcome is. If you need more help at that stage, I'll help where I can.

**Comment by HelenHHH** [comment]
I'd love to "clone Pyrit" and then "rebuilt it".   Where do I start?

I was hoping a future release of Pyrit would simply be fixed, instead.

(After I get this working again... what is the long-term prevention?  Just to NEVER update/upgrade anything in Kali ever again?)

**Comment by JPaulMora** [comment]
no, absolutely not. Ideally, as with any python project, it should be ported to python 3. That is not always easy though.

**Comment by RFKiller** [comment]
@HelenHHH - you should always keep your system patched and updated. If you want to clone Pyrit and rebuild it using Python 2 (like Kali should have done), then right here is the place to start.

Clone Pyrit from GitHub, then simply start building using the instructions.
