### ISSUE TITLE
Pyrit NO GPU with ArchLinux

### ISSUE THREAD

**Issue by darkstaring** [JPaulMora/Pyrit#519]
Hello, i installed this package
--
aur/cpyrit-cuda-git 0.5.0.r21.g6111f10-1 [installed: 0.5.0.r26.g6cf2c12-1] (14) (0.22)
aur/cpyrit-opencl-git 0.5.0.r26.g6cf2c12-2 [installed] (14) (0.45)
aur/pyrit-git 0.5.0.r21.g6111f10-1 [installed: 0.5.0.r26.g6cf2c12-1] (33) (0.22)
--
cuda 8.0.44-3
nvidia 375.26-6
nvidia-cg-toolkit 3.1-4
nvidia-libgl 375.26-2
nvidia-settings 375.26-1
nvidia-utils 375.26-2
opencl-nvidia 375.26-2
--

But pyrit list_cores says only cpu core...
i try edit setup.py, and add 
OPENCL_INC_DIRS = ['/opt/cuda/include/']
OPENCL_LIB_DIRS = ['/opt/cuda/lib64/']
and
'/opt/cuda/include/' 
in "for path in" 
but not work....

Can you help me
Thank you

**Comment by JPaulMora** [comment]
Have you enabled CUDA in the config?

**Comment by darkstaring** [comment]
how to...

**Comment by JPaulMora** [comment]
open file `~/.pyrit/config`

**Comment by RFKiller** [comment]
I am having the exact same issue on Arch Linux however setting CUDA to "true" in both cpyrit/config.py and ~/.pyrit/config, but am still getting no GPU power with Pyrit.

Computed 1718.40 PMKs/s total.
#1: 'CPU-Core (SSE2/AES)': 467.8 PMKs/s (RTT 3.1)
#2: 'CPU-Core (SSE2/AES)': 474.4 PMKs/s (RTT 3.0)
#3: 'CPU-Core (SSE2/AES)': 475.1 PMKs/s (RTT 3.0)
#4: 'CPU-Core (SSE2/AES)': 470.1 PMKs/s (RTT 3.1)
CUDA:

**Comment by darkstaring** [comment]
you have cuda  and nvidia driver?

**Comment by RFKiller** [comment]
`you have cuda and nvidia driver?`
Yes I do. Both installed and confirmed working just fine.

**Comment by RFKiller** [comment]
I'm confused - is this issue still open or not? Because I've read a few instances of Pyrit with CUDA not working for Arch Linux users. If it is still open, and someone would like the fix, then please let me know and I will post it.

**Comment by sawmj** [comment]
@ghost yes it doesn't work for me if you, do you know how to get it work ?

**Comment by sersajar** [comment]
I have installed the same stuff as the post creator, and does not work, tried too to compile from source, and nothing too... CUDA is enabled in cofig file...

I get this error when I try to analyze a cap file:

Failed to load Pyrit's OpenCL-core ('Failed to enumerate OpenCL-platforms (Unknown CLresult)').
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Traceback (most recent call last):
  File "/usr/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/lib/python2.7/site-packages/pyrit_cli.py", line 117, in initFromArgv
    func(self, **options)
  File "/usr/lib/python2.7/site-packages/pyrit_cli.py", line 160, in new_f
    import cpyrit.pckttools
  File "/usr/lib/python2.7/site-packages/cpyrit/pckttools.py", line 132, in <module>
    scapy.packet.bind_layers(scapy.layers.l2.EAPOL, EAPOL_Key, type=3)
AttributeError: 'module' object has no attribute 'EAPOL'
[sscorpio@Alien-One hs]$ primusrun pyrit -r handshake_MOVISTARC333_34-57-60-6D-C3-34_2018-04-26T04-10-25.cap analyze
Failed to load Pyrit's OpenCL-core ('Failed to enumerate OpenCL-platforms (Unknown CLresult)').
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Traceback (most recent call last):
  File "/usr/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/lib/python2.7/site-packages/pyrit_cli.py", line 117, in initFromArgv
    func(self, **options)
  File "/usr/lib/python2.7/site-packages/pyrit_cli.py", line 160, in new_f
    import cpyrit.pckttools
  File "/usr/lib/python2.7/site-packages/cpyrit/pckttools.py", line 132, in <module>
    scapy.packet.bind_layers(scapy.layers.l2.EAPOL, EAPOL_Key, type=3)
AttributeError: 'module' object has no attribute 'EAPOL'
