### ISSUE TITLE
Can't Install Cpyrit-cuda Can't Use Cpyrit-opencl

### ISSUE THREAD

**Issue by HEndLess** [JPaulMora/Pyrit#520]
My operating system is Kali Linux.
I installed nvidia-kernel-dkms, nvidia-cuda, nvidia-opencl, nvidia-xserver, bumblebee (I have 2 graphic cards on my laptop), optirun.
When I try to install cpyrit-cuda i get this error:

root@hel:~# cd Desktop/Pyrit/modules/cpyrit_cuda/
root@hel:~/Desktop/Pyrit/modules/cpyrit_cuda# python setup.py build
The CUDA compiler and headers required to build kernel were not found. Trying to continue anyway...
running build
running build_ext
Compiling CUDA module using nvcc 8.0, V8.0.44...
Executing 'nvcc -m64 -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
ERROR: No supported gcc/g++ host compiler found, but clang-3.8 is available.
       Use 'nvcc -ccbin clang-3.8' to use that instead.
Traceback (most recent call last):
  File "setup.py", line 168, in <module>
    setup(**setup_args)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 91, in run
    subprocess.check_call(nvcc_cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'nvcc -m64 -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu' returned non-zero exit status 1

I installed cpyrit-opencl. When i try to run pyrit list_cores i get this error:

root@hel:~# optirun pyrit list_cores
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 118, in initFromArgv
    func(self, **options)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 295, in list_cores
    with cpyrit.cpyrit.CPyrit() as cp:
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 449, in __init__
    p = _cpyrit_opencl.OpenCLPlatform(platform_idx)
SystemError: Failed to enumerate devices on this platform (CL_DEVICE_NOT_FOUND)

here is my config:

default_storage = file://
limit_ncpus = 0
rpc_announce = true
rpc_announce_broadcast = false
rpc_knownclients = 
rpc_server = false
use_CUDA = false
use_OpenCL = true
workunit_size = 75000

Please help me. I am trying to make pyrit work with gpu for a week.

**Comment by Malencor** [comment]
Hello

I am also having issues on this step.

From what I've been able to gather Kali linux 2 is now running on gcc version 6.3 if you take a look at the /usr/local/cuda/bin there are two files one is g++ and one is gcc when I read them they both say they open or can proceed with version 4.8, 4.9, and version 5 or else use clang-3.8.

I don't know how to use clang-3.8 but I have been trying to get any of 4.8, 4.9, 5 to work but to no avail
do you have any idea as to how to work with the gcc?

Also what else have you tried?

Oh BTW since 5.0 they added a .config file in [.pyrit](https://github.com/JPaulMora/Pyrit/releases) which you have to or should assing a true or false statement to either using 

use_CUDA = true or false           // To MY understanding for NVidia
use_OpenCL = true or false       // To MY understanding for AMD

TBH it probably wont solve the issue but once the issue is resolved having this set up right might avoid chasing ones own tail on something that will already be working.

**Comment by RFKiller** [comment]
@HEndLess - You are trying to build a program with Python 3 when Pyrit was actually programmed in Python 2 a long time ago when Python 3 didn't even exist yet. But now, many many years later, we have Python 3 as default for nearly every distribution under the sun, even LTS distros. So you need to build Pyrit with Python2.x instead of the default installation of Python3.x used by Kali and all other distros now. So when you try to build Pyrit with:
```
# python setup.py build
```
Kali is defaulting to Python3.x to use python3-setuptools when it should be using Python2.x and python2-setuptools to build Pyrit like this instead:
```
# python2 setup.py build
# python2 setup.py install
```
It should be no more difficult than that.

@Malencor - yes you are correct that in ~/.pyrit/config you need to set "use_CUDA = true" to use Nvidia GPU and OpenCL is used for ATI/AMD GPUs

**Comment by Malencor** [comment]
@RFKiller 

Is there anything you suggest I try as far something I'm missing
or
maybe am I hitting my head against a problem which has no solution as of yet
or
pointing me in the right direction to get this working?

Regardless thank you for taking the time to help.

**Comment by RFKiller** [comment]
You would have to open a new issue and copy/paste your own error messages and possible logs before anyone can begin to help debugging.

**Comment by girbotphone** [comment]
I've been searching and searching because I've come across this same issue. I used to run Pyrit with CUDA support on an older distribution of Kali. I recently had to reformat that drive and installed the newer version of Kali on it. I ran into an issue I didn't have before and have been going crazy for the last month over it:
I get the same long message, the most important part of which is: 
ERROR: No supported gcc/g++ host compiler found, but clang-3.8 is available.
Use 'nvcc -ccbin clang-3.8' to use that instead.

As far as I can tell, this is not a python compile issue, this is a gcc issue. I've tried this whole process so many times and recorded the process and I can ensure that I've used "python2" as well as "python". In my experience that hasn't made any difference. If what I've been reading is correct, nvcc versions support a narrow range of compilers, and gcc 6 is too modern for that cut, exactly as Malencor said. I've been looking for a work around, but I haven't been able to solve this myself yet. Some have suggested installing multiple gcc versions, downloading and compiling from source, but I'm honestly not sure how to go about managing that process. I haven't been able to resolve this yet. I don't think it's a Pyrit issue in and of itself, but it probably deserves a troubleshooting footnote and workaround reference.

**Comment by JPaulMora** [comment]
Actually, @girbotphone that's a nvcc issue. The cuda toolkits are made for certain versions of gcc only. You can install alt versions from the default Kali repos, or from ubuntu 16.10 repos.

**Comment by RFKiller** [comment]
@girbotphone have you tried just doing what it recommends first? Which is to attempt a build of Pyrit using the Clang compiler instead of GCC? I have personally never used Clang except for 1 time when it first came out (just to see if compiling was any faster or easier versus GCC). So I can't say what will happen. Edit the Pyrit source to use clang instead of GCC with something like sed or another text stream editor.

`root@kali: ~ # sed -i s'/original-text/replacement-text/' file.txt`

When you say you don't know how to build from source, do you mean you don't know how to compile Pyrit from source? Or GCC? Both should have complete documentation regarding how to build, and what compiling options are available. But as JPaulMora already said, you can probably find alternative versions already in the repositories.

Lastly, GCC-6 is not too modern for NVCC. I use Arch Linux, which uses GCC-6 by default (I built Pyrit using GCC verion 6.3.1). And I had no NVCC issues at all when I built Pyrit with CUDA. If you're going to try another GCC version, I would not use the Ubuntu repositories, however. Use the Debian repos because Kali is essentially a rolling release of Debian (testing?). You can find the deb files on the Debian website so that you don't even to compile from sauce.
https://packages.debian.org/search?keywords=gcc-6

**Comment by girbotphone** [comment]
I've included my error output, which, unless I'm missing something, is the same as the original potser's, so I think it's still relevant. I've gone through and documented an installation process up to the error. If I've made an error somewhere in my process, I'd like to be able to pin-point it. 

Error Code:

a@a:~/Pyrit/modules/cpyrit_cuda#

 python2 setup.py build
The CUDA compiler and headers required to build kernel were not found. Trying to continue anyway...
running build
running build_ext
Compiling CUDA module using nvcc 8.0, V8.0.44...
Executing 'nvcc -m64 -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
ERROR: No supported gcc/g++ host compiler found, but clang-3.8 is available.
       Use 'nvcc -ccbin clang-3.8' to use that instead.
Traceback (most recent call last):
  File "setup.py", line 168, in <module>
    setup(**setup_args)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 91, in run
    subprocess.check_call(nvcc_cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'nvcc -m64 -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu' returned non-zero exit status 1

I've pieced this process together through a variety of guides. It might be excessive, but better descriptive than not enough info. I've tried plenty of other things, this just seems to be the fastest, most direct route. 
From fresh install of modern Kali:
`apt-get update && apt-get upgrade -y && apt-get dist-upgrade -y`
finding the current headers with apt-cache search, in this case:
`apt-get install linux-headers-4.9.0-kali3-common`
`apt-get install nvidia-kernel-common`
`apt-get install nvidia-kernel-dkms`
`apt-get install nvidia-xconfig`
`nvidia-xconfig`
`reboot`
The Nvidia Linux Long lived driver is successfully installed, tested to confirm with `lsmod | grep nvidia` on reboot. Continuing:
`apt-get install nvidia-cuda-toolkit nvidia-opencl-icd`
Tested wtih `nvcc --version` and output:
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Sun_Sep__4_22:14:01_CDT_2016
Cuda compilation tools, release 8.0, V8.0.44`
Moving on to Pyrit:
`apt-get remove pyrit`
`git clone https://github.com/JPaulMora/Pyrit.git`
`cd Pyrit`
several items needed to be installed, apparently resulting in a trial and error lib lookup and install..
libssl-dev and zlib1g-dev, for example. after those are installed...
`python2 setup.py build`
`python2 setup.py install`
`pyrit`
And pyrit works, no problems there.
`cd /root/Pyrit/modules/cpyrit_cuda`
`python2 setup.py build`

and that's where we end up... error.
gcc is what you'd expect:
`gcc --version:
gcc (Debian 6.3.0-6) 6.3.0 20170205`

An apt-cache search lists a lot of options for gcc, but the oldest option is 4.9 with my current standing. I'm not sure if I need to add to the repo, if cuda just isn't configured or installed right, if i need to use an alternate compiler, or what. I'm just really not sure how to negotiate beyond this point. Thank you both for your input so far, I've been battling with this on and off for weeks.

**Comment by RFKiller** [comment]
I can confirm now that using `nvcc -ccbin clang-3.8` works just fine on Debian and more specifically on Kali. Just open the "setup.py" file and change the "NVCC" variable which will be invoked later by nvcc_cmd. Then it builds just fine with Clang instead of using GCC.

**Comment by andronixist** [comment]
Hello rfkiller, I'm having same issue with trying to install cpyrit. Could you please explain your last message again. Which variable should I change to get this to work . Thank you very much for your help

**Comment by RFKiller** [comment]
@andronixist - No, I can't really explain the last message again. It explains itself. The only thing I can do explain it in a more convoluted way. If the simple instructions don't make sense, neither will the convoluted and more complex instructions. JPaulMora already said in another post he will be adding Clang to the nvcc variable to automate it whether you have GCC or Clang installed. Just wait for the next release or do a Git update and see if the changes are already made.

**Comment by RFKiller** [comment]
@andronixist - Actually I just checked, and you could have done the same. He already added clang to the setup.py file.

[https://github.com/JPaulMora/Pyrit/blob/master/modules/cpyrit_cuda/setup.py](https://github.com/JPaulMora/Pyrit/blob/master/modules/cpyrit_cuda/setup.py)

**Comment by JPaulMora** [comment]
So @andronixist, just `cd` into your cloned Pyrit folder and run `git pull` then try to install again

**Comment by andronixist** [comment]
Hello again. That was all I needed!  I updated setup.py and it worked perfectly! Thank you very much.

**Comment by JPaulMora** [comment]
Great to hear that! anything else feel free to reach out

**Comment by HEndLess** [comment]
Hi! I totally forgot here. And hotmail moved emails on "other" category. I just saw the solutions you sent. I tried to use python2 and I got different error and I tried this link : https://github.com/JPaulMora/Pyrit/blob/master/modules/cpyrit_cuda/setup.py and i think it worked. But still there is a problem. I tried pyrit list_cores and I get this error = 

NVIDIA: no NVIDIA devices found
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 118, in initFromArgv
    func(self, **options)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 295, in list_cores
    with cpyrit.cpyrit.CPyrit() as cp:
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 449, in __init__
    p = _cpyrit_opencl.OpenCLPlatform(platform_idx)
SystemError: Failed to enumerate devices on this platform (CL_DEVICE_NOT_FOUND)
 
So I decided to do everything again from zero. But I think I tried to many times to install cpyrit and now I can't remove old installation. I tried apt-get remove pyrit but it didn't work. I think that happens because of I installed it on python. So can you tell me how to remove it so I can start over?

**Comment by RFKiller** [comment]
Just remove everything that has to do with pyrit by using "find" and "rm". Then start from scratch. Something like `find / -name "*pyrit*" | rm` or however you want to do it.

**Comment by JPaulMora** [comment]
When you run `setup.py install` it tells you where the files where copied to. Go to that directory and manually delete all Pyrit files. I do not entirely recommend @RFKiller command because (based on experience) you may delete the wrong files if you make a typo, instead run find first and once you're sure you want to delete what `find` lists, add the `rm` part

**Comment by HEndLess** [comment]
Well, thank you very much for your help. It did work. After all these persistent trying now I can see my graphic card :

WARNING: Unknown option 'use_CUDA' in configfile '/root/.pyrit/config'
WARNING: Unknown option 'use_OpenCL' in configfile '/root/.pyrit/config'
/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py:63: UserWarning: WARNING: Version mismatch between <module 'cpyrit._cpyrit_cpu' from '/usr/local/lib/python2.7/dist-packages/cpyrit/_cpyrit_cpu.so'> ('0.4.0') and <module 'cpyrit._cpyrit_cuda' from '/usr/local/lib/python2.7/dist-packages/cpyrit/_cpyrit_cuda.so'> ('0.5.0')

  "('%s')\n" % (_cpyrit_cpu, _cpyrit_cpu.VERSION, mod, ver))
Pyrit 0.4.0 (C) 2008-2011 Lukas Lueg http://pyrit.googlecode.com
This code is distributed under the GNU General Public License v3+

The following cores seem available...
#1:  'CUDA-Device #1 'GeForce 940M''
#2:  'CPU-Core (SSE2)'
#3:  'CPU-Core (SSE2)'
#4:  'CPU-Core (SSE2)'

I get some warning messages but it doesn't matter. I can get (31478.4 PMKs/s)... That's the important thing.

**Comment by JPaulMora** [comment]
Thats great! although it seems that you still have an outdated core module (0.4.0) you may wanna delete Pyrit completely and reinstall now that you know how. Just run `sudo rm -rf /usr/local/lib/python2.7/dist-packages/*pyrit*` that should remove all pyrit related files. Once reinstalled, the warnings should be gone.

**Comment by HEndLess** [comment]
Alright, I will do that. Thanks again for your help.
