### ISSUE TITLE
Nvidia Cuda Issue

### ISSUE THREAD

**Issue by Rapt0r445** [JPaulMora/Pyrit#560]
Hi Guys i am having a bit of an issue istalling Pyrit on my Nvidia enabled laptop.

I followed the install instructions and had no errors during installation.
My laptop Specs are Nvidia 940M and have used Pyrit before without issue but i reinstalled my Ubuntu OS and thus had to reinstall Pyrit.

I have the latest Nvidia and Cuda Drivers.

After the install is complete (no errors) i run Pyrit and it loads normally but my problem occurs when i run "pyrit list_cores" or "pyrit benchmark" after enabling cuda in the config file.

chris@laptop~$ pyrit list_cores
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 117, in initFromArgv
    func(self, **options)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 294, in list_cores
    with cpyrit.cpyrit.CPyrit() as cp:
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 442, in __init__
    self.CUDAs.append(CUDACore(queue=self, dev_idx=dev_idx))
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 243, in __init__
    _cpyrit_cuda.CUDADevice.__init__(self, dev_idx)
SystemError: Unknown CUresult.

chris@laptop:~$ pyrit benchmark
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 117, in initFromArgv
    func(self, **options)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 1193, in benchmark
    with cpyrit.cpyrit.CPyrit() as cp:
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 442, in __init__
    self.CUDAs.append(CUDACore(queue=self, dev_idx=dev_idx))
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 243, in __init__
    _cpyrit_cuda.CUDADevice.__init__(self, dev_idx)
SystemError: Unknown CUresult.

What's happening, i don't know how to fix this

Hope someone can help

**Comment by Hackitfree** [comment]
https://github.com/JPaulMora/Pyrit/issues/553
