### ISSUE TITLE
Error analyzing .cap files.

### ISSUE THREAD

**Issue by RubenPOR** [JPaulMora/Pyrit#565]
I am just trying to check if a captured handshake is ok, but I get the error bellow.
Using the strip option results in the exact same error.
My python version is: (2.7.12-1ubuntu0~16.04.3)
Am I doing something wrong?

$ pyrit -r zon.cap analyze
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 117, in initFromArgv
    func(self, **options)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 160, in new_f
    import cpyrit.pckttools
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 132, in <module>
    scapy.packet.bind_layers(scapy.layers.l2.EAPOL, EAPOL_Key, type=3)
AttributeError: 'module' object has no attribute 'EAPOL'

**Comment by ShellBear** [comment]
The problem comes from scapy's update. I personnaly solved the problem by downgrading scapy using pip. Here an example command: 

``
wget -O /tmp/scapy2.3.2.tar.gz https://pypi.python.org/packages/6d/72/c055abd32bcd4ee6b36ef8e9ceccc2e242dea9b6c58fdcf2e8fd005f7650/scapy-2.3.2.tar.gz; sudo pip2 install /tmp/scapy2.3.2.tar.gz
``

**Comment by sersajar** [comment]
Not in my case, I tried and nothing different happens...

**Comment by arismelachroinos** [comment]
@ShellBear 
Fixed my issue! Thanks!
