### ISSUE TITLE
Failed to load Pyrit's OpenCL-core 

### ISSUE THREAD

**Issue by sersajar** [JPaulMora/Pyrit#566]
I tried to install pyrit in many different ways, compiling it from source (stable), installing from a graphical interface from Antergos linux(git version and default), and downloading through the terminal with yaourt and/or pacman...  

The first problem I found and solved quickly, is the traceback: 
scapy is not installed...

Easy to solve: install libraries and python2 version of python-scapy.

Next issue is where I am stuck....
Nvidia driver is correctly installed, scapy and all libraries too. And Cuda toolkit 9 is also installed. Cpyrit is theorically installed but my system does not found it (i use Antergos Linux, based in linux arch)

When I type : python -c 'from cpyrit import _cpyrit_opencl'
I get this traceback:

Failed to load Pyrit's OpenCL-core ('Failed to enumerate OpenCL-platforms (Unknown CLresult)').
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name _cpyrit_opencl

[sscorpio@Alien-One cpyrit]$ python -c 'from cpyrit import _cpyrit_cuda'
Failed to load Pyrit's OpenCL-core ('Failed to enumerate OpenCL-platforms (Unknown CLresult)').
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name _cpyrit_cuda

The same if I look for cpyrit_cuda.

Anybody knows how to fix it, or what i am doing wrong? Thanks in advance and pardon me if this issue is duplicated. Feel free to link me to the old thread.

**Comment by Hackitfree** [comment]
You have to make pyrit yourself...Uninstall Pyrit and follow my guide..
Check to have all this installed 👍 


apt install nvidia-driver ocl-icd-libopencl1 nvidia-cuda-toolkit

apt install mesa-utils nvidia-cuda-gdb nvidia-cuda-doc libssl-dev zlib1g-dev libpcap-dev libgl1-nvidia-glx python2.7-dev python-pycuda-doc python-pycuda python3-pycuda

reboot

*Pyrit prep

git clone https://github.com/JPaulMora/Pyrit.git

gedit /root/.bashrc

*Add these lines to the end of .bashrc

PATH=$PATH:/usr/lib/nvidia-cuda-toolkit/bin.
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/nvidia-cuda-toolkit/lib:/lib
export PATH
export LD_LIBRARY_PATH

*Pyrit_Cuda Prep and Install

cd /root/Pyrit/modules/cpyrit_cuda/

gedit setup.py

Edit the setup.py, line 35,edit it from*

for path in ('/usr/local/cuda', '/opt/cuda'):

*to:

for path in ('/usr/local/cuda','/usr/lib/nvidia-cuda-toolkit','/opt/cuda'):

line 88,edit it from**

nvcc_cmd = NVCC + bit_flag + ' -ccbin clang -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'

nvcc_cmd = NVCC + bit_flag + ' -ccbin clang-3.8 -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'

*then

cd /root/Pyrit

*and install

python setup.py clean build install

*last thing

gedit /root/.pyrit/config

*change from:

use_CUDA = false

*to

use_CUDA = true

*now check your GPU

pyrit list_cores

ENJOY !!!

*Note: GPU works best with 1 CPU core
gedit /root/.pyrit/config
*set:
limit_ncpus = 1

**Comment by sersajar** [comment]
I am going to follow your guide, is mandatory to do all the steps as root??

**Comment by sersajar** [comment]
Ok, I followed all steps, (almost, some stuff to install is missing in arch repos, like nvidia-cuda-gdb). And i got this traceback when I do pyrit -r file.cap analyze:

Traceback (most recent call last):
  File "/usr/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/lib/python2.7/site-packages/pyrit_cli.py", line 117, in initFromArgv
    func(self, **options)
  File "/usr/lib/python2.7/site-packages/pyrit_cli.py", line 160, in new_f
    import cpyrit.pckttools
  File "/usr/lib/python2.7/site-packages/cpyrit/pckttools.py", line 132, in <module>
    scapy.packet.bind_layers(scapy.layers.l2.EAPOL, EAPOL_Key, type=3)
AttributeError: 'module' object has no attribute 'EAPOL'

When I try to install cpyrit_cuda, from the git repository I cloned before, and after editing setup.py, I do python2 setup.py clean build install, and I get this:

running clean
Removing temporary files and pre-built GPU-kernels...
running build
running build_ext
Compiling CUDA module using nvcc 9.1, V9.1.85...
Executing '/opt/cuda/bin/nvcc -m64 -ccbin clang-3.8 -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'
clang-3.8: No such file or directory
Traceback (most recent call last):
  File "setup.py", line 166, in <module>
    setup(**setup_args)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 91, in run
    subprocess.check_call(nvcc_cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/cuda/bin/nvcc -m64 -ccbin clang-3.8 -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu' returned non-zero exit status 1

Is it possible that clang is missing? I gonna try to install clang, now...

**Comment by Hackitfree** [comment]
Try not to modify the line with clang 3.8 ...Try with the original setup file and tell me how it compiles please :)

**Comment by Hackitfree** [comment]
Just leave the line like it was:
nvcc_cmd = NVCC + bit_flag + ' -ccbin clang -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'

**Comment by sersajar** [comment]
I tried too.... : 

running clean
Removing temporary files and pre-built GPU-kernels...
running build
running build_ext
Compiling CUDA module using nvcc 9.1, V9.1.85...
Executing '/opt/cuda/bin/nvcc -m64 -ccbin clang -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'
nvcc fatal   : The version ('60000') of the host compiler ('clang') is not supported
Traceback (most recent call last):
  File "setup.py", line 166, in <module>
    setup(**setup_args)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 91, in run
    subprocess.check_call(nvcc_cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/cuda/bin/nvcc -m64 -ccbin clang -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu' returned non-zero exit status 1

**Comment by sersajar** [comment]
I does not support version 6.000    it is rare...! Trie to install version 3.8 or 3.9, but the signature pgp fails.....

**Comment by Hackitfree** [comment]
Hmm..So sorry..Check pgp signature..On newest versin of Kali this wouldnt be a problem at all..I dont know what version kali you have..Let me check if i find that signature so i can help ....

**Comment by Hackitfree** [comment]
wget -q -O - https://archive.kali.org/archive-key.asc  | apt-key add 


For the key try this

**Comment by sersajar** [comment]
I can use pyrit perfectly in wifislax or kali, but I wanted to use it in my custom made linux, based on linux arch. Will try to download clang and llvm 3.8 from its website and compile from source....

**Comment by Hackitfree** [comment]
Wish you luck dude-sorry if i couldnt help enough :)

**Comment by sersajar** [comment]
Any help is always welcome!! :D Thanks again.
