### ISSUE TITLE
SortedCollection error when analyzing captured handshake

### ISSUE THREAD

**Issue by yadox666** [JPaulMora/Pyrit#570]
Hi all.

In the last downloaded release 0.5.1, even after uninstalling it and reinstalling it, I got an error that I don't know how to solve. Can you please help me?

root@laptop586:/home/yadox/Descargas/Pyrit-master/test# ./test_pyrit.py 
Testing with filesystem-storage...
testAnalyze (__main__.FilesystemTestCase) ... WARNING: No route found for IPv6 destination :: (no default route?)
ERROR
testAttackBatch (__main__.FilesystemTestCase) ... ERROR
testAttackCowpatty (__main__.FilesystemTestCase) ... ERROR
testAttackDB (__main__.FilesystemTestCase) ... ERROR
testAttackPassthrough (__main__.FilesystemTestCase) ... ERROR
testBatch (__main__.FilesystemTestCase) ... ok
testBatchWithFile (__main__.FilesystemTestCase) ... ok
testBenchmark (__main__.FilesystemTestCase) ... ok
testCheckDB (__main__.FilesystemTestCase) ... Error in workunit 26b8e459fc41b8ce40c468d9f91f9866: Digest check failed
Error in workunit 3cf20217a3a697eced94fb6c5149eb20: Digest check failed
Error in workunit 652fb4e7ffa13552585cb4a6c35ad812: Not a PAW2-buffer.
Error in workunit 39dd7e6df49ede0b10e303a7350a6bba: Digest check failed
Error in workunit 12ab637438ca3da6469fe22ad0af5881: Not a PAW2-buffer.
Error in workunit 404a2ea04920feda097dea1c1300af0d: Not a PAW2-buffer.
Error in workunit b4a648af4fb8bc52e34d303537571d48: Digest check failed
Error in workunit 5c31b308d0e5a6bebcf0920b5bf0ee6a: Not a PAW2-buffer.
Error in results d0e17c45f9c94222a7d0e993edf2206f for ESSID 'test': Not a PYR2-buffer.
Error in results 2e26c2fcd48651ee4678acf5d63b8319 for ESSID 'test': Not a PYR2-buffer.
Error in results 81a6b9ed7896d801f371046f582750b7 for ESSID 'test': pmkbuffer seems truncated
Error in results 086cf99d3872d83b2ab988586fe5af12 for ESSID 'test': Reference error
Error in results 2e4f7f325bbaf18061fd23e64e269014 for ESSID 'test': pmkbuffer seems truncated
Error in results a5ac4e74fa84e1407c28cec9ce5c46b9 for ESSID 'test': pmkbuffer seems truncated
Error in results f752245887f42497d7a9c5e75bc1a397 for ESSID 'test': Not a PYR2-buffer.
Error in results b40e7b8250c22d840556acfa040e4afa for ESSID 'test': Reference error
Error in results ef9b1b7babe9a2cba1d2f088fa5a48be for ESSID 'test': pmkbuffer seems truncated
Error in results 8f4b5668fce13a77f52503c19639a68d for ESSID 'test': Not a PYR2-buffer.
Error in results 4449a11567a850ca72e790a3933d2a11 for ESSID 'test': Reference error
Error in results c8a298334e791539199c4709bb386a57 for ESSID 'test': Reference error
Error in results c2012082971bca0e870ed1a6c47066e9 for ESSID 'test': pmkbuffer seems truncated
Error in results 6a8e8b3b71fb59bb726a060194cd37a7 for ESSID 'test': Reference error
Error in results 6cc1af32f4568a4b1c8ed4a22c737176 for ESSID 'test': Not a PYR2-buffer.
Error in results b66bb16f0ef9610b3e31bfbaaa4a70e3 for ESSID 'test': Not a PYR2-buffer.
Error in results 08165f1bf5d3bb1f5d875a0d690210df for ESSID 'test': pmkbuffer seems truncated
Error in results 38a480138bc2f7b47e208987966f6598 for ESSID 'test': pmkbuffer seems truncated
ok
testCreateAndDeleteEssid (__main__.FilesystemTestCase) ... ok
testEval (__main__.FilesystemTestCase) ... ok
testExportCowpatty (__main__.FilesystemTestCase) ... ok
testExportHashdb (__main__.FilesystemTestCase) ... ok
testExportPasswords (__main__.FilesystemTestCase) ... ok
testHandshakes (__main__.FilesystemTestCase) ... ERROR
testImportPasswords (__main__.FilesystemTestCase) ... ok
testListCores (__main__.FilesystemTestCase) ... ok
testListEssids (__main__.FilesystemTestCase) ... ok
testPassthrough (__main__.FilesystemTestCase) ... ok
testPrintHelp (__main__.FilesystemTestCase) ... ok
testSelfTest (__main__.FilesystemTestCase) ... ok
testStripCapture (__main__.FilesystemTestCase) ... ERROR
testStripLive (__main__.FilesystemTestCase) ... ERROR
testVerify (__main__.FilesystemTestCase) ... Workunit 6acd4f31aae065057bf2b9cb7d1b4933 for ESSID 'test' is corrupt.
Workunit 5db20041a8728b832784fe327d1acc1a for ESSID 'test' is corrupt.
Workunit d509a7f9fd29ae96e50c03733805de5d for ESSID 'test' is corrupt.
Workunit 12e77ff43a051da9652bdd88861902bc for ESSID 'test' is corrupt.
Workunit 1dca672ce42508351912b5139ea9e94b for ESSID 'test' is corrupt.
Workunit 3043c0427f3851a2767f47eed995e43d for ESSID 'test' is corrupt.
Workunit cdd8b7e80d6d06ff0c9e7329584c4ae3 for ESSID 'test' is corrupt.
Workunit 31a9b75606266f5ad448ebd4d5936d03 for ESSID 'test' is corrupt.
Workunit f35d53f479326e1c7159c71fa0434642 for ESSID 'test' is corrupt.
Workunit 84f6038f076d7811be0bc2b029cb6d50 for ESSID 'test' is corrupt.
Workunit 321f2b5654860c1800ea3287e9c488fb for ESSID 'test' is corrupt.
Workunit c3cbe64bc9dbb23703b635925aef0099 for ESSID 'test' is corrupt.
Workunit ec93af6dcbf61ec5e6888cc6e7e637fb for ESSID 'test' is corrupt.
Workunit ec256b7d3ec0fa98959153d6f2f41fb6 for ESSID 'test' is corrupt.
Workunit c553f956f1b5cb201d9e10d7e2098532 for ESSID 'test' is corrupt.
Workunit 4fa0fadc3225ff6a95d2a074bdc52506 for ESSID 'test' is corrupt.
Workunit 99b6d41e8859905fcc2b8bbbe69dd80f for ESSID 'test' is corrupt.
Workunit 932b026d032dde9e085e97aeeb7ba051 for ESSID 'test' is corrupt.
Workunit bd011d025827d38031bf506c147468aa for ESSID 'test' is corrupt.
Workunit b5bb5cf80c0318457f21bacf7833e9ad for ESSID 'test' is corrupt.
Workunit 15e682314365a84c13ca3dfa9128637c for ESSID 'test' is corrupt.
Workunit 99b6d5ba88188bec18a87f28bb8e2fda for ESSID 'test' is corrupt.
Workunit c418f00d93d2cfa10ea1c0a067cead28 for ESSID 'test' is corrupt.
ok

======================================================================
ERROR: testAnalyze (__main__.FilesystemTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_pyrit.py", line 59, in new_f
    import cpyrit.pckttools
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 169, in <module>
    class SCSortedCollection(util.SortedCollection):
AttributeError: 'module' object has no attribute 'SortedCollection'

======================================================================
ERROR: testAttackBatch (__main__.FilesystemTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_pyrit.py", line 59, in new_f
    import cpyrit.pckttools
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 169, in <module>
    class SCSortedCollection(util.SortedCollection):
AttributeError: 'module' object has no attribute 'SortedCollection'

======================================================================
ERROR: testAttackCowpatty (__main__.FilesystemTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_pyrit.py", line 59, in new_f
    import cpyrit.pckttools
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 169, in <module>
    class SCSortedCollection(util.SortedCollection):
AttributeError: 'module' object has no attribute 'SortedCollection'

======================================================================
ERROR: testAttackDB (__main__.FilesystemTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_pyrit.py", line 59, in new_f
    import cpyrit.pckttools
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 169, in <module>
    class SCSortedCollection(util.SortedCollection):
AttributeError: 'module' object has no attribute 'SortedCollection'

======================================================================
ERROR: testAttackPassthrough (__main__.FilesystemTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_pyrit.py", line 59, in new_f
    import cpyrit.pckttools
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 169, in <module>
    class SCSortedCollection(util.SortedCollection):
AttributeError: 'module' object has no attribute 'SortedCollection'

======================================================================
ERROR: testHandshakes (__main__.FilesystemTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_pyrit.py", line 59, in new_f
    import cpyrit.pckttools
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 169, in <module>
    class SCSortedCollection(util.SortedCollection):
AttributeError: 'module' object has no attribute 'SortedCollection'

======================================================================
ERROR: testStripCapture (__main__.FilesystemTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_pyrit.py", line 59, in new_f
    import cpyrit.pckttools
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 169, in <module>
    class SCSortedCollection(util.SortedCollection):
AttributeError: 'module' object has no attribute 'SortedCollection'

======================================================================
ERROR: testStripLive (__main__.FilesystemTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_pyrit.py", line 59, in new_f
    import cpyrit.pckttools
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 169, in <module>
    class SCSortedCollection(util.SortedCollection):
AttributeError: 'module' object has no attribute 'SortedCollection'

----------------------------------------------------------------------
Ran 24 tests in 69.122s

FAILED (errors=8)

**Comment by pavonis9** [comment]
**Take a look at :** https://github.com/JPaulMora/Pyrit/issues/584#issuecomment-522239316
if it works close the issue.
