### ISSUE TITLE
Can't install Pyrit with driver 397.54+cuda 9.2

### ISSUE THREAD

**Issue by darksty** [JPaulMora/Pyrit#577]
sames there is some new feature with cuda 9.2 so i can't install Pyrit..

the issue prompt that "clang" will not be supported any more

**Comment by darksty** [comment]
running clean
Removing temporary files and pre-built GPU-kernels...
running build
running build_ext
Compiling CUDA module using nvcc 9.2, V9.2.148...
Executing '/usr/local/cuda/bin/nvcc -m64 -ccbin clang -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'
nvcc fatal   : The version ('6.0') of the host compiler ('clang') is not supported
Traceback (most recent call last):
  File "setup.py", line 166, in <module>
    setup(**setup_args)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 91, in run
    subprocess.check_call(nvcc_cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/cuda/bin/nvcc -m64 -ccbin clang -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu' returned non-zero exit status 1

**Comment by darksty** [comment]
The good news is i am using opencl now .and that is also fast an cuda..

Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Running benchmark (130442.7 PMKs/s)... \ 

Computed 130442.71 PMKs/s total.
#1: 'CPU-Core (SSE2/AES)': 673.9 PMKs/s (RTT 3.0)
#2: 'CPU-Core (SSE2/AES)': 646.3 PMKs/s (RTT 3.1)
#3: 'CPU-Core (SSE2/AES)': 662.6 PMKs/s (RTT 2.9)
#4: 'CPU-Core (SSE2/AES)': 644.5 PMKs/s (RTT 3.1)
#5: 'CPU-Core (SSE2/AES)': 647.6 PMKs/s (RTT 2.9)
#6: 'CPU-Core (SSE2/AES)': 659.4 PMKs/s (RTT 2.9)
#7: 'CPU-Core (SSE2/AES)': 642.8 PMKs/s (RTT 3.2)
#8: 'CPU-Core (SSE2/AES)': 662.0 PMKs/s (RTT 3.0)
OpenCL:
#1: 'OpenCL-Device 'GeForce GTX TITAN X'': 140144.1 PMKs/s (RTT 1.2)
