### ISSUE TITLE
To install cpyrit-cuda you need to remove "-ccbin clang" from modules/cpyrit_cuda/setup.py

### ISSUE THREAD

**Issue by hlechner** [JPaulMora/Pyrit#581]
It does return error when I try to install the cpyrit:

> Executing '/opt/cuda/bin/nvcc -m64 -ccbin clang -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'
nvcc fatal   : The version ('7.0') of the host compiler ('clang') is not supported
Traceback (most recent call last):
  File "setup.py", line 166, in <module>
    setup(**setup_args)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 91, in run
    subprocess.check_call(nvcc_cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/cuda/bin/nvcc -m64 -ccbin clang -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu' returned non-zero exit status 1

To solve it I ended up removing the arguments: `-ccbin clang` from modules/cpyrit_cuda/setup.py

@JPaulMora I choose not send a Pull Request since I don't know how it will affect other systems.

**Comment by vido89** [comment]
I did not removed it just chage it to  -ccbin clang-3.8, Im on ubuntu 16.04
