### ISSUE TITLE
Error when listing cores

### ISSUE THREAD

**Issue by alvertosk** [JPaulMora/Pyrit#582]
Hi! I just got the following error when trying to list my cores (and confirm that pyrit can detecty my gpu. Also I would like to note that using the command python -c 'from cpyrit import _cpyrit_cuda' I get no errors or output.

root@host:~# python -c 'from cpyrit import _cpyrit_cuda'
root@host:~# pyrit list_cores
Pyrit 0.5.0 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 117, in initFromArgv
    func(self, **options)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 294, in list_cores
    with cpyrit.cpyrit.CPyrit() as cp:
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 441, in __init__
    CUDA =  cpyrit_cuda.listDevices()
NameError: global name 'cpyrit_cuda' is not defined

I did find a similar error but it is not exactly the same so I thought I should post it here. 

Thank you in advance for your time!

**Comment by lsergei** [comment]
Got the same issue. I know it's been a while, but have you managed to resolve it?

**Comment by alvertosk** [comment]
Never did. I went to hashcat.... Sorry @JPaulMora!
