### ISSUE TITLE
SystemError: Unknown CUresult.

### ISSUE THREAD

**Issue by u666sa** [JPaulMora/Pyrit#595]
I followed proper installation instructions, looked at different issues.  My system is Ubuntu 18.04. clang3.9, cuda 9.1. 390.123 driver. Kernel 5.3.

`$ pyrit list_cores
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 117, in initFromArgv
    func(self, **options)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 294, in list_cores
    with cpyrit.cpyrit.CPyrit() as cp:
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 442, in __init__
    self.CUDAs.append(CUDACore(queue=self, dev_idx=dev_idx))
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 243, in __init__
    _cpyrit_cuda.CUDADevice.__init__(self, dev_idx)
SystemError: Unknown CUresult.`

`pyrit benchmark
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Running benchmark (3423.0 PMKs/s)... / 

Computed 3422.99 PMKs/s total.
#1: 'CPU-Core (SSE2)': 393.3 PMKs/s (RTT 3.1)
OpenCL:
#1: 'OpenCL-Device 'GeForce GT 420M'': 3397.7 PMKs/s (RTT 2.8)
`

**Comment by u666sa** [comment]
SOLVED

This error means that your linux installation has improper version of CUDA installed.  For example, my Ubuntu 18.04 LTS had CUDA 9.1 installed, however my card GeForce 420M had a maximum support of CUDA 8.0.  Installing proper CUDA version solved the problem.
