### ISSUE TITLE
undefined symbol: aesni_key

### ISSUE THREAD

**Issue by vido89** [JPaulMora/Pyrit#597]
Im on ubuntu 18.04 and I getting this error

```
pyrit 
Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 4, in <module>
    import pyrit_cli
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 32, in <module>
    import cpyrit.cpyrit
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 42, in <module>
    import util
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/util.py", line 54, in <module>
    import _cpyrit_cpu
ImportError: /usr/local/lib/python2.7/dist-packages/cpyrit/_cpyrit_cpu.so: undefined symbol: aesni_key
```

**Comment by vido89** [comment]
I needed to remove pyrit manually 
```

/.
/usr
/usr/bin
/usr/bin/pyrit
/usr/lib
/usr/lib/python2.7
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/cpyrit
/usr/lib/python2.7/dist-packages/cpyrit/__init__.py
/usr/lib/python2.7/dist-packages/cpyrit/_cpyrit_cpu.x86_64-linux-gnu.so
/usr/lib/python2.7/dist-packages/cpyrit/config.py
/usr/lib/python2.7/dist-packages/cpyrit/cpyrit.py
/usr/lib/python2.7/dist-packages/cpyrit/network.py
/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py
/usr/lib/python2.7/dist-packages/cpyrit/storage.py
/usr/lib/python2.7/dist-packages/cpyrit/util.py
/usr/lib/python2.7/dist-packages/pyrit-0.4.0.egg-info
/usr/lib/python2.7/dist-packages/pyrit_cli.py
/usr/share
/usr/share/doc
/usr/share/doc/pyrit
/usr/share/doc/pyrit/README
/usr/share/doc/pyrit/README.Debian
/usr/share/doc/pyrit/TODO.Debian
/usr/share/doc/pyrit/changelog.Debian.gz
/usr/share/doc/pyrit/copyright
/usr/share/doc/pyrit/examples
/usr/share/doc/pyrit/examples/config.example
/usr/share/doc/pyrit/examples/wpa2psk-2WIRE972.dump.gz
/usr/share/doc/pyrit/examples/wpa2psk-MOM1.dump.gz
/usr/share/doc/pyrit/examples/wpa2psk-Red_Apple.dump.gz
/usr/share/doc/pyrit/examples/wpa2psk-linksys.dump.gz
/usr/share/doc/pyrit/examples/wpapsk-linksys.dump.gz
/usr/share/doc/pyrit/examples/wpapsk-virgin_broadband.dump.gz
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/pyrit
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/pyrit.1.gz
```

**Comment by perseo001** [comment]
Same issue Kali linux 2020.1 
pyrit
Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 4, in <module>
    import pyrit_cli
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 32, in <module>
    import cpyrit.cpyrit
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 42, in <module>
    import util
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/util.py", line 54, in <module>
    import _cpyrit_cpu
ImportError: /usr/local/lib/python2.7/dist-packages/cpyrit/_cpyrit_cpu.so: undefined symbol: aesni_key

**Comment by m00-git** [comment]
Same issue using the latest version of Parrot Security

**Comment by m00-git** [comment]
The thread on the same problem here: https://github.com/JPaulMora/Pyrit/issues/591
solved issue.

**Comment by debiantano** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 4, in <module>
    import pyrit_cli
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 32, in <module>
    import cpyrit.cpyrit
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 42, in <module>
    import util
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/util.py", line 54, in <module>
    import _cpyrit_cpu
ImportError: /usr/local/lib/python2.7/dist-packages/cpyrit/_cpyrit_cpu.so: undefined symbol: aesni_key


Tengo este problema ,alguna solucion  :(
