### ISSUE TITLE
issue afer install pyrit

### ISSUE THREAD

**Issue by fernando-cg** [JPaulMora/Pyrit#614]
Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 4, in <module>
    import pyrit_cli
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 32, in <module>
    import cpyrit.cpyrit
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 42, in <module>
    import util
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/util.py", line 54, in <module>
    import _cpyrit_cpu
ImportError: /usr/local/lib/python2.7/dist-packages/cpyrit/_cpyrit_cpu.so: undefined symbol: aesni_key

**Comment by Herakules1999** [comment]
dont work :"/ please help

**Comment by shadowjynxs** [comment]
The easy fix would be editing the _cpyrit_cpu.c file or alternatively do this : sed -i "s/COMPILE_AESNI/COMPILE_AESNIX/" _cpyrit_cpu.c

**Comment by syedzada077** [comment]
not working
