### ISSUE TITLE
Can't parse a file

### ISSUE THREAD

**Issue by VladislavNekto** [JPaulMora/Pyrit#633]
```
orange@PC:~/wificrack$ pyrit -r pcap-05.cap analyze
Pyrit 0.5.0 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Parsing file 'pcap-05.cap' (1/1)...
Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/local/lib64/python2.7/site-packages/pyrit_cli.py", line 117, in initFromArgv
    func(self, **options)
  File "/usr/local/lib64/python2.7/site-packages/pyrit_cli.py", line 166, in new_f
    f(*args, **kwds)
  File "/usr/local/lib64/python2.7/site-packages/pyrit_cli.py", line 466, in analyze
    parser = self._getParser(capturefile)
  File "/usr/local/lib64/python2.7/site-packages/pyrit_cli.py", line 182, in _getParser
    parser.parse_pcapdevice(dev)
  File "/usr/local/lib64/python2.7/site-packages/cpyrit/pckttools.py", line 714, in parse_pcapdevice
    self.parse_packet(pckt)
  File "/usr/local/lib64/python2.7/site-packages/cpyrit/pckttools.py", line 732, in parse_packet
    self._add_ap(dot11_pckt.addr2, dot11_pckt)
  File "/usr/local/lib64/python2.7/site-packages/cpyrit/pckttools.py", line 660, in _add_ap
    essid = self._find_ssid(pckt)
  File "/usr/local/lib64/python2.7/site-packages/cpyrit/pckttools.py", line 652, in _find_ssid
    if elt_pckt.isFlagSet('ID', 'SSID') \
  File "/usr/local/lib64/python2.7/site-packages/cpyrit/pckttools.py", line 80, in isFlagSet
    if val not in field.i2s:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by kevinixz** [comment]
Same output here, any solution?

**Comment by kevinixz** [comment]
Sole solution https://github.com/JPaulMora/Pyrit/commit/14ec997174b8e8fd20d22b6a97c57e19633f12a0#r42177738
