### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by syedzada077** [JPaulMora/Pyrit#651]
Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 4, in <module>
    import pyrit_cli
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 32, in <module>
    import cpyrit.cpyrit
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 42, in <module>
    import util
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/util.py", line 54, in <module>
    import _cpyrit_cpu
ImportError: /usr/local/lib/python2.7/dist-packages/cpyrit/_cpyrit_cpu.so: undefined symbol: aesni_key

**Comment by adbuuras** [comment]
i have a same problem !!!

**Comment by JPaulMora** [comment]
This has been fixed, also Pyrit3 (for python3) has been released
