### ISSUE TITLE
Pyrit --help error

### ISSUE THREAD

**Issue by 1xTP** [JPaulMora/Pyrit#661]
I have installed pyrit using the instructions on the wiki. I have tried with both git clone and the latest release (0.5.0). When running "pyrit --help" I get the following error.

Using the pyrit-installer script from hacker3983 works perfectly fine on Kali Linux. I am currently using Zorin os but I've had this issue even when trying to install on Kali. Adding uninstallation instructions to the wiki would also be useful.

```Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 4, in <module>
    import pyrit_cli
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 32, in <module>
    import cpyrit.cpyrit
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 41, in <module>
    import util
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/util.py", line 53, in <module>
    import _cpyrit_cpu
ImportError: /usr/local/lib/python2.7/dist-packages/cpyrit/_cpyrit_cpu.so: undefined symbol: aesni_key

**Comment by JPaulMora** [comment]
Hi this has been fixed, but also Pyrit3 (for python3) has been released
